const fs = require("fs");
const path = require("path");

module.exports = (opt, destPath, cb) => {
    fs.writeFile(path.join(destPath, "README.md"),
        `
# ${opt.title || ""}
## ${opt.name}@${opt.version}

${opt.description || ""}

${opt.author || ""}

generated by **smartface** 2018.
    `, "utf-8", cb);
};
